apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: jz0q3k733-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: jz0q3k733-python 
  name: jz0q3k733-python
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: jz0q3k733-python
    weight: 100 
